the_codeine_user:

scheb_two_factor:
    google:
        enabled: false
        template: TheCodeineUserBundle:TwoStepAuthentication:form.html.twig
    email:
        enabled: false
        sender_email: no-reply@example.com
        sender_name: John Doe  # Optional
        digits: 6
        template: TheCodeineUserBundle:TwoStepAuthentication:form.html.twig
    access_control:
        - { path: ^/admin/ }
        - { path: ^/login }