fos_user_security_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    methods:  [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_change_password:
    path: /admin/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
