services:
    tuna.user.password.reset:
        class: TheCodeine\UserBundle\EventListener\PasswordChangingListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }